### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchFieldError: totalHits trying to create a index using the GBIF Taxonomy backbone

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/ala-name-matching#137]
Trying to generate an up-to-date index of the [GBIF Backbone Taxonomy](https://hosted-datasets.gbif.org/datasets/backbone/backbone-current.zip) compatible with the new `ala-namematching-service` and `pipelines:`

`./index.sh --all --dwca ../gbif-backbone/ --target /data/lucene/gbif-2021-pipelines-namematching `

I get this exception:

``` 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data/lucene/ala-name-matching/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data/lucene/ala-name-matching/lib/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
WARN : [TermFactory] - Terms dcterms:references and gbif:Reference are both known as "references". Keeping only dcterms:references
WARN : [TermFactory] - Terms dcterms:contributor and http://purl.org/dc/elements/1.1/contributor are both known as "contributor". Keeping only dcterms:contributor
WARN : [TermFactory] - Terms dcterms:coverage and http://purl.org/dc/elements/1.1/coverage are both known as "coverage". Keeping only dcterms:coverage
WARN : [TermFactory] - Terms dcterms:creator and http://purl.org/dc/elements/1.1/creator are both known as "creator". Keeping only dcterms:creator
WARN : [TermFactory] - Terms dcterms:date and http://purl.org/dc/elements/1.1/date are both known as "date". Keeping only dcterms:date
WARN : [TermFactory] - Terms dcterms:description and http://purl.org/dc/elements/1.1/description are both known as "description". Keeping only dcterms:description
WARN : [TermFactory] - Terms dcterms:format and http://purl.org/dc/elements/1.1/format are both known as "format". Keeping only dcterms:format
WARN : [TermFactory] - Terms dcterms:identifier and http://purl.org/dc/elements/1.1/identifier are both known as "identifier". Keeping only dcterms:identifier
WARN : [TermFactory] - Terms dcterms:language and http://purl.org/dc/elements/1.1/language are both known as "language". Keeping only dcterms:language
WARN : [TermFactory] - Terms dcterms:publisher and http://purl.org/dc/elements/1.1/publisher are both known as "publisher". Keeping only dcterms:publisher
WARN : [TermFactory] - Terms dcterms:relation and http://purl.org/dc/elements/1.1/relation are both known as "relation". Keeping only dcterms:relation
WARN : [TermFactory] - Terms dcterms:rights and http://purl.org/dc/elements/1.1/rights are both known as "rights". Keeping only dcterms:rights
WARN : [TermFactory] - Terms dcterms:source and http://purl.org/dc/elements/1.1/source are both known as "source". Keeping only dcterms:source
WARN : [TermFactory] - Terms dcterms:subject and http://purl.org/dc/elements/1.1/subject are both known as "subject". Keeping only dcterms:subject
WARN : [TermFactory] - Terms dcterms:title and http://purl.org/dc/elements/1.1/title are both known as "title". Keeping only dcterms:title
WARN : [TermFactory] - Terms dcterms:type and http://purl.org/dc/elements/1.1/type are both known as "type". Keeping only dcterms:type
WARN : [TermFactory] - Terms dwc:scientificNameID and ala:nameID are both known as "nameid". Keeping only dwc:scientificNameID
INFO : [DwcaNameIndexer] - Generating loading index: true
INFO : [DwcaNameIndexer] - Generating searching index: true
INFO : [DwcaNameIndexer] - Using the  DwCA name file: ../gbif-backbone/
INFO : [DwcaNameIndexer] - Using the default IRMNG name file: /data/lucene/sources/IRMNG_DWC_HOMONYMS
WARN : [DwcaNameIndexer] - No common name export specified and the default file path does not exist or is inaccessible. Default path: /data/lucene/sources/col_vernacular.txt
WARN : [DwcaNameIndexer] - No priorities file, defaulting to uniform priorities.
WARN : [DwcaNameIndexer] - No identifiers file, Defailts is /data/lucene/sources/identifiers.txt
INFO : [DwcaNameIndexer] - Target directory already exists. Backing up to : /data/lucene/gbif-2021-pipelines-namematching_2021-11-25_01-03-34
INFO : [DwcaNameIndexer] - Base sources: [../gbif-backbone]
INFO : [DwcaNameIndexer] - Loading DwCAs: [../gbif-backbone]
INFO : [DwcaNameIndexer] - Starting to create the temporary loading index for ../gbif-backbone
INFO : [DwcaNameIndexer] - Finished creating the temporary load index with 0 concepts
INFO : [DwcaNameIndexer] - Loading index from temporary index.
Exception in thread "main" java.lang.NoSuchFieldError: totalHits
        at au.org.ala.names.search.DwcaNameIndexer.generateIndex(DwcaNameIndexer.java:599)
        at au.org.ala.names.search.DwcaNameIndexer.main(DwcaNameIndexer.java:1168)
```

Any tip? TIA!

**Comment by vjrj** [comment]
Using the README updated for #136 the 4.0 release starts to work for me:

```
(...)
INFO : [DwcaNameIndexer] - Target directory already exists. Backing up to : /data/lucene/gbif-2021-pipelines-namematching_2021-11-26_08-36-12
INFO : [DwcaNameIndexer] - Base sources: [../gbif-backbone]
INFO : [DwcaNameIndexer] - Loading DwCAs: [../gbif-backbone]
INFO : [DwcaNameIndexer] - Starting to create the temporary loading index for ../gbif-backbone
INFO : [DwcaNameIndexer] - Finished creating the temporary load index with 6923610 concepts
INFO : [DwcaNameIndexer] - Loading index from temporary index.
INFO : [DwcaNameIndexer] - Finished loading root 8 Viruses left:2 right:17449 root count:0
INFO : [DwcaNameIndexer] - Finished loading root 0 incertae sedis left:17450 right:22191 root count:1
```
