### ISSUE TITLE
Non-latin characters in vernaular name indexing

### ISSUE THREAD

**Issue by cjk-halodule** [AtlasOfLivingAustralia/ala-name-matching#77]
https://github.com/AtlasOfLivingAustralia/ala-name-matching/blob/60ba7247d121d308225068bdd914da8df2f676a5/src/main/java/au/org/ala/names/search/ALANameIndexer.java#L762

This line seems omitting non-latin characters when indexing vernacular names, which is crucial for some countries, e.g. east Asian languages, to adopt ALA stacks.

**Comment by charvolant** [comment]
Agreed. I'll revisit the vernacular name management.

Do you have a couple of examples that I could use?

**Comment by cjk-halodule** [comment]
Yes - here is the national checklist dwca from Taiwan that I use during the workshop.
The last few lines of error message are:
```
2019-04-03 15:01:28,494 INFO : [DwcaNameIndexer] - Loading synonyms for /data/lucene/sources/dwca-taicol
2019-04-03 15:01:29,228 INFO : [DwcaNameIndexer] - Loading vernacular for /data/lucene/sources/dwca-taicol
2019-04-03 15:01:29,228 INFO : [DwcaNameIndexer] - Starting to load the common names extension from /data/lucene/sources/dwca-taicol
java.lang.NullPointerException
	at au.org.ala.names.search.ALANameIndexer.createCommonNameDocument(ALANameIndexer.java:762)
	at au.org.ala.names.search.DwcaNameIndexer.indexCommonNameExtension(DwcaNameIndexer.java:386)
	at au.org.ala.names.search.DwcaNameIndexer.create(DwcaNameIndexer.java:210)
	at au.org.ala.names.search.DwcaNameIndexer.main(DwcaNameIndexer.java:1160)
```
And attached the DwC-A here. Thanks for taking a look.
[dwca-taicol.zip](https://github.com/AtlasOfLivingAustralia/ala-name-matching/files/3042141/dwca-taicol.zip)
